name: Deploy to dev and prod
on:
  push:
    branches:
      - master
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/sykmeldinger-backendproxy:${{ github.sha }}
jobs:
  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build Docker image
        run: |
          docker build -t ${IMAGE} .
      - name: Login to Github Package Registry
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin docker.pkg.github.com
      - name: Push Docker image
        run: |
          docker push ${IMAGE}
#      - name: deploy sykmeldinger-backend to prod-sbs
#        uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-sbs
#          RESOURCE: sykmeldinger-backend/nais.yaml
